# =============================================================================
# okBATHTUB - Visualization Functions
# Oklahoma Water Resources Board - Water Quality Division
#
# Exported functions:
#   ok_plot_response()   - load-response curve (TP -> Chl-a or TSI)
#   ok_plot_scenario()   - scenario comparison bar/dot chart
#   ok_plot_segments()   - longitudinal segment profile
#   ok_plot_tsi()        - Carlson TSI diagram with trophic bands
#   ok_theme()           - shared ggplot2 theme
#   ok_trophic_colors()  - trophic state color palette
# =============================================================================

# Declare global variables used in ggplot2 aes() calls to avoid R CMD check notes
utils::globalVariables(c(
  "metric", "point_color", "tsi_chla", "tsi_secchi", "tsi_tp", "xmin", "xmax"
))


# =============================================================================
# SHARED THEME AND PALETTE
# =============================================================================

#' Oklahoma water-themed ggplot2 palette
#'
#' @description
#' Named color vector for trophic state classifications used consistently
#' across all okBATHTUB plots.
#'
#' @return Named character vector of hex colors.
#' @export
ok_trophic_colors <- function() {
  c(
    "Oligotrophic"   = "#2196A6",   # teal blue
    "Mesotrophic"    = "#4CAF82",   # green
    "Eutrophic"      = "#F4A623",   # amber
    "Hypereutrophic" = "#D9534F"    # red
  )
}


#' Oklahoma water-themed ggplot2 theme
#'
#' @description
#' A clean, minimal ggplot2 theme used consistently across all okBATHTUB
#' visualization functions. Based on \code{theme_minimal()} with clean
#' typography and grid settings.
#'
#' @param base_size Numeric. Base font size. Default 11.
#' @param legend_position Character. Legend position. Default \code{"bottom"}.
#'
#' @return A \code{ggplot2::theme} object.
#' @export
ok_theme <- function(base_size = 11, legend_position = "bottom") {
  ggplot2::theme_minimal(base_size = base_size) +
  ggplot2::theme(
    plot.title         = ggplot2::element_text(face = "bold", size = base_size + 1),
    plot.subtitle      = ggplot2::element_text(color = "grey40", size = base_size - 1),
    plot.caption       = ggplot2::element_text(color = "grey55", size = base_size - 2,
                                               hjust = 0),
    axis.title         = ggplot2::element_text(size = base_size - 0.5),
    panel.grid.minor   = ggplot2::element_blank(),
    panel.grid.major.x = ggplot2::element_blank(),
    legend.position    = legend_position,
    legend.title       = ggplot2::element_text(face = "bold", size = base_size - 1),
    strip.text         = ggplot2::element_text(face = "bold")
  )
}


# =============================================================================
# 1. ok_plot_response() - Load-response curve
# =============================================================================

#' Plot a load-response curve for a reservoir
#'
#' @description
#' \code{ok_plot_response()} generates a load-response curve showing how
#' predicted in-lake chlorophyll-a, Secchi depth, or mean TSI responds to
#' a range of inflow total phosphorus concentrations. This is the core
#' planning tool for answering "what inflow TP concentration achieves
#' a given trophic state target?"
#'
#' The curve is generated by running the full okBATHTUB pipeline across a
#' sequence of TP concentrations while holding all other parameters constant
#' at the baseline values.
#'
#' @param baseline An \code{okBATHTUB} object that has been run through at
#'   least \code{ok_hydraulics()}. Morphometry and coefficient set are
#'   taken from this object.
#' @param response One of \code{"chla"} (chlorophyll-a, ug/L),
#'   \code{"secchi"} (Secchi depth, m), \code{"tsi"} (mean Carlson TSI),
#'   or \code{"tp_inlake"} (in-lake TP, ug/L). Default \code{"chla"}.
#' @param tp_range Numeric vector of length 2. Range of inflow TP
#'   concentrations to plot (ug/L). Default \code{c(10, 300)}.
#' @param n_points Integer. Number of points along the curve. Default 100.
#' @param target_tsi Numeric. Optional horizontal reference line showing a
#'   TSI target. Only shown when \code{response = "tsi"}.
#' @param target_class Character. Trophic class target. Sets
#'   \code{target_tsi} automatically. One of \code{"oligotrophic"},
#'   \code{"mesotrophic"}, \code{"eutrophic"}.
#' @param show_trophic_bands Logical. Show coloured trophic state background
#'   bands on TSI plots. Default \code{TRUE} when response is \code{"tsi"}.
#' @param current_tp Numeric. Optional vertical reference line showing the
#'   current inflow TP concentration.
#' @param lake_name Character. Lake name for plot title. Default \code{NULL}.
#'
#' @return A \code{ggplot2} object.
#'
#' @examples
#' \dontrun{
#' baseline <- ok_load(
#'   inflow_m3yr   = 45e6,
#'   tp_inflow_ugl = 120,
#'   coefficients  = "oklahoma",
#'   ecoregion     = "Cross Timbers"
#' ) |>
#' ok_hydraulics(surface_area_ha = 890, mean_depth_m = 4.2)
#'
#' ok_plot_response(baseline, response = "tsi",
#'                  target_class = "mesotrophic",
#'                  current_tp   = 120,
#'                  lake_name    = "Arcadia Lake")
#' }
#'
#' @seealso \code{\link{ok_scenario}}, \code{\link{ok_plot_scenario}}
#' @export

ok_plot_response <- function(baseline,
                              response           = c("chla", "secchi",
                                                     "tsi", "tp_inlake"),
                              tp_range           = c(10, 300),
                              n_points           = 100L,
                              target_tsi         = NULL,
                              target_class       = NULL,
                              show_trophic_bands = NULL,
                              current_tp         = NULL,
                              lake_name          = NULL) {

  if (!requireNamespace("ggplot2", quietly = TRUE))
    stop("Package 'ggplot2' is required. Install with: install.packages('ggplot2')",
         call. = FALSE)

  assert_okBATHTUB(baseline)
  response <- match.arg(response)

  if (!is.null(target_class) && is.null(target_tsi)) {
    target_tsi <- switch(tolower(target_class),
                          "oligotrophic" = 40, "mesotrophic" = 50,
                          "eutrophic"    = 70, NULL)
  }

  if (is.null(show_trophic_bands))
    show_trophic_bands <- (response == "tsi")

  d    <- baseline$data
  meta <- baseline$meta

  # Build TP sequence
  tp_seq <- seq(tp_range[1], tp_range[2], length.out = n_points)

  # Run pipeline for each TP value
  curve_df <- do.call(rbind, lapply(tp_seq, function(tp) {
    r <- ok_load(
      inflow_m3yr   = d$inflow_m3yr,
      tp_inflow_ugl = tp,
      tn_inflow_ugl = d$tn_inflow_ugl,
      coefficients  = meta$coefficients %||% "walker",
      ecoregion     = meta$ecoregion
    ) |>
    ok_hydraulics(
      surface_area_ha = d$surface_area_ha,
      mean_depth_m    = d$mean_depth_m,
      outflow_m3yr    = d$outflow_m3yr
    ) |>
    ok_retention() |>
    ok_inlake()    |>
    ok_tsi()

    data.frame(
      tp_inflow  = tp,
      tp_inlake  = r$data$tp_inlake_ugl  %||% NA_real_,
      chla       = r$data$chla_ugl        %||% NA_real_,
      secchi     = r$data$secchi_m        %||% NA_real_,
      tsi        = r$data$tsi_mean        %||% NA_real_,
      tsi_tp     = r$data$tsi_tp          %||% NA_real_,
      state      = r$data$trophic_state   %||% NA_character_
    )
  }))

  # Y-axis setup
  y_col   <- switch(response,
                     chla       = "chla",
                     secchi     = "secchi",
                     tsi        = "tsi",
                     tp_inlake  = "tp_inlake")
  y_label <- switch(response,
                     chla       = "Predicted Chlorophyll-a (ug/L)",
                     secchi     = "Predicted Secchi Depth (m)",
                     tsi        = "Mean Carlson TSI",
                     tp_inlake  = "Predicted In-Lake TP (ug/L)")

  pal <- ok_trophic_colors()

  title_str <- if (!is.null(lake_name)) {
    sprintf("%s \u2014 Load-Response Curve", lake_name)
  } else {
    "Load-Response Curve"
  }

  coeff_label <- if (!is.null(meta$coefficients)) meta$coefficients else "walker"
  eco_label   <- if (!is.null(meta$ecoregion)) meta$ecoregion else "statewide"

  subtitle_str <- sprintf(
    "Coefficients: %s | Ecoregion: %s | HRT: %.2f yr | Area: %.0f ha",
    coeff_label, eco_label,
    d$hydraulic_residence_time_yr %||% NA,
    d$surface_area_ha %||% NA
  )

  p <- ggplot2::ggplot(curve_df,
                        ggplot2::aes(x = tp_inflow, y = .data[[y_col]]))

  # Trophic state bands (TSI only)
  if (show_trophic_bands && response == "tsi") {
    band_df <- data.frame(
      ymin  = c(0,  40, 50, 70),
      ymax  = c(40, 50, 70, 100),
      state = c("Oligotrophic", "Mesotrophic", "Eutrophic", "Hypereutrophic")
    )
    p <- p +
      ggplot2::geom_rect(
        data        = band_df,
        ggplot2::aes(xmin = -Inf, xmax = Inf,
                     ymin = ymin,  ymax = ymax,
                     fill = state),
        alpha       = 0.12,
        inherit.aes = FALSE
      ) +
      ggplot2::scale_fill_manual(
        values = pal,
        name   = "Trophic State",
        guide  = ggplot2::guide_legend(order = 2)
      )
  }

  # Main response curve
  p <- p +
    ggplot2::geom_line(color = "#1B5E8A", linewidth = 1.1) +
    ggplot2::labs(
      title    = title_str,
      subtitle = subtitle_str,
      x        = "Inflow TP (ug/L)",
      y        = y_label,
      caption  = "okBATHTUB R package"
    ) +
    ok_theme()

  # TSI target line
  if (!is.null(target_tsi) && response == "tsi") {
    target_label <- if (!is.null(target_class)) {
      sprintf("%s target (TSI = %.0f)", tools::toTitleCase(target_class),
              target_tsi)
    } else {
      sprintf("TSI target = %.0f", target_tsi)
    }
    p <- p +
      ggplot2::geom_hline(yintercept = target_tsi,
                           linetype = "dashed", color = "#D9534F",
                           linewidth = 0.8) +
      ggplot2::annotate("text", x = tp_range[1] + diff(tp_range) * 0.02,
                         y = target_tsi + 1.5, label = target_label,
                         hjust = 0, size = 3.2, color = "#D9534F")
  }

  # Current TP reference line
  if (!is.null(current_tp)) {
    p <- p +
      ggplot2::geom_vline(xintercept = current_tp,
                           linetype = "dotted", color = "grey30",
                           linewidth = 0.8) +
      ggplot2::annotate("text", x = current_tp + diff(tp_range) * 0.01,
                         y = max(curve_df[[y_col]], na.rm = TRUE) * 0.97,
                         label = sprintf("Current\nTP = %.0f ug/L",
                                         current_tp),
                         hjust = 0, size = 3.0, color = "grey30")
  }

  p
}


# =============================================================================
# 2. ok_plot_scenario() - Scenario comparison
# =============================================================================

#' Plot scenario comparison from ok_scenario() output
#'
#' @description
#' \code{ok_plot_scenario()} visualises the output of \code{ok_scenario()} or
#' \code{ok_scenario_sweep()} as a faceted dot-and-line chart, showing how
#' key water quality metrics change across loading scenarios.
#'
#' @param scenario_result A data frame returned by \code{ok_scenario()} or
#'   \code{ok_scenario_sweep()}.
#' @param metrics Character vector. Which metrics to plot. Any subset of
#'   \code{c("tp_inlake_ugl", "chla_ugl", "secchi_m", "tsi_mean")}.
#'   Default: all four.
#' @param highlight_target Logical. If the scenario result contains a
#'   \code{meets_target} column, highlight scenarios that meet the target
#'   in green. Default \code{TRUE}.
#' @param lake_name Character. Lake name for the plot title.
#'
#' @return A \code{ggplot2} object.
#'
#' @examples
#' \dontrun{
#' baseline <- ok_load(inflow_m3yr = 45e6, tp_inflow_ugl = 120,
#'                      coefficients = "oklahoma",
#'                      ecoregion    = "Cross Timbers") |>
#'   ok_hydraulics(surface_area_ha = 890, mean_depth_m = 4.2)
#'
#' sweep <- ok_scenario_sweep(baseline, target_class = "mesotrophic")
#' ok_plot_scenario(sweep, lake_name = "Arcadia Lake")
#' }
#'
#' @seealso \code{\link{ok_scenario}}, \code{\link{ok_scenario_sweep}}
#' @export

ok_plot_scenario <- function(scenario_result,
                              metrics          = c("tp_inlake_ugl", "chla_ugl",
                                                   "secchi_m", "tsi_mean"),
                              highlight_target = TRUE,
                              lake_name        = NULL) {

  if (!requireNamespace("ggplot2", quietly = TRUE))
    stop("Package 'ggplot2' is required.", call. = FALSE)
  if (!requireNamespace("tidyr", quietly = TRUE))
    stop("Package 'tidyr' is required.", call. = FALSE)
  if (!requireNamespace("dplyr", quietly = TRUE))
    stop("Package 'dplyr' is required.", call. = FALSE)

  if (!is.data.frame(scenario_result))
    stop("'scenario_result' must be a data frame from ok_scenario().",
         call. = FALSE)

  metric_labels <- c(
    tp_inlake_ugl = "In-Lake TP (ug/L)",
    chla_ugl      = "Chlorophyll-a (ug/L)",
    secchi_m      = "Secchi Depth (m)",
    tsi_mean      = "Mean Carlson TSI"
  )

  # Keep only metrics that exist in the data and were requested
  metrics <- intersect(metrics, names(scenario_result))
  metrics <- intersect(metrics, names(metric_labels))

  if (length(metrics) == 0)
    stop("None of the requested metrics are present in scenario_result.",
         call. = FALSE)

  # Pivot to long format
  has_target <- "meets_target" %in% names(scenario_result) && highlight_target

  keep_cols <- c("scenario", metrics,
                  if (has_target) "meets_target" else NULL)

  long_df <- scenario_result[, keep_cols, drop = FALSE] |>
    tidyr::pivot_longer(
      cols      = dplyr::all_of(metrics),
      names_to  = "metric",
      values_to = "value"
    ) |>
    dplyr::mutate(
      metric_label = metric_labels[metric],
      metric_label = factor(metric_label, levels = metric_labels[metrics]),
      scenario     = factor(scenario, levels = rev(unique(scenario_result$scenario)))
    )

  if (has_target) {
    long_df <- long_df |>
      dplyr::mutate(
        point_color = dplyr::if_else(meets_target, "Meets target", "Does not meet target")
      )
  }

  title_str <- if (!is.null(lake_name)) {
    sprintf("%s \u2014 Scenario Comparison", lake_name)
  } else {
    "Scenario Comparison"
  }

  p <- ggplot2::ggplot(
    long_df,
    ggplot2::aes(x = value, y = scenario)
  ) +
    ggplot2::facet_wrap(
      ~ metric_label,
      scales = "free_x",
      ncol   = 2
    )

  if (has_target) {
    p <- p +
      ggplot2::geom_point(
        ggplot2::aes(color = point_color),
        size = 3.5
      ) +
      ggplot2::scale_color_manual(
        values = c("Meets target"        = "#4CAF82",
                   "Does not meet target" = "#1B5E8A"),
        name   = NULL
      )
  } else {
    p <- p +
      ggplot2::geom_point(color = "#1B5E8A", size = 3.5)
  }

  # Highlight baseline row
  baseline_y <- which(levels(long_df$scenario) == "Baseline")
  if (length(baseline_y) > 0) {
    p <- p +
      ggplot2::geom_hline(
        yintercept = baseline_y,
        linetype   = "dashed",
        color      = "grey60",
        linewidth  = 0.5
      )
  }

  p <- p +
    ggplot2::labs(
      title   = title_str,
      x       = NULL,
      y       = NULL,
      caption = "okBATHTUB R package"
    ) +
    ok_theme(legend_position = "top")

  p
}


# =============================================================================
# 3. ok_plot_segments() - Longitudinal profile
# =============================================================================

#' Plot a longitudinal water quality profile across reservoir segments
#'
#' @description
#' \code{ok_plot_segments()} visualises the spatial gradient in water quality
#' from riverine to lacustrine zones of a multi-segment reservoir, using the
#' output of \code{ok_segment_summary()} or \code{ok_segment_chain()}.
#'
#' @param segment_data Either a named list of \code{okBATHTUB} objects from
#'   \code{ok_segment_chain()}, or a data frame from \code{ok_segment_summary()}.
#' @param metrics Character vector. Which metrics to plot. Any subset of
#'   \code{c("tp_inlake_ugl", "chla_ugl", "secchi_m", "tsi_mean",
#'   "tp_retention_pct")}. Default: first four.
#' @param lake_name Character. Lake name for the plot title.
#'
#' @return A \code{ggplot2} object.
#'
#' @examples
#' \dontrun{
#' segs <- list(
#'   list(label = "Riverine",     surface_area_ha = 280, mean_depth_m = 3.1),
#'   list(label = "Transitional", surface_area_ha = 410, mean_depth_m = 4.5),
#'   list(label = "Lacustrine",   surface_area_ha = 610, mean_depth_m = 5.8)
#' )
#' chain <- ok_segment_chain(45e6, 150, tn_inflow_ugl = 2200, segments = segs)
#' ok_plot_segments(chain, lake_name = "Example Reservoir")
#' }
#'
#' @seealso \code{\link{ok_segment_chain}}, \code{\link{ok_segment_summary}}
#' @export

ok_plot_segments <- function(segment_data,
                              metrics    = c("tp_inlake_ugl", "chla_ugl",
                                             "secchi_m", "tsi_mean"),
                              lake_name  = NULL) {

  if (!requireNamespace("ggplot2", quietly = TRUE))
    stop("Package 'ggplot2' is required.", call. = FALSE)
  if (!requireNamespace("tidyr", quietly = TRUE))
    stop("Package 'tidyr' is required.", call. = FALSE)
  if (!requireNamespace("dplyr", quietly = TRUE))
    stop("Package 'dplyr' is required.", call. = FALSE)

  # Accept either a chain list or a summary data frame
  if (is.list(segment_data) && !is.data.frame(segment_data)) {
    df <- ok_segment_summary(segment_data)
  } else if (is.data.frame(segment_data)) {
    df <- segment_data
  } else {
    stop("'segment_data' must be a list from ok_segment_chain() or a data frame from ok_segment_summary().",
         call. = FALSE)
  }

  metric_labels <- c(
    tp_inlake_ugl    = "In-Lake TP (ug/L)",
    chla_ugl         = "Chlorophyll-a (ug/L)",
    secchi_m         = "Secchi Depth (m)",
    tsi_mean         = "Mean Carlson TSI",
    tp_retention_pct = "TP Retention (%)"
  )

  metrics <- intersect(metrics, names(df))
  metrics <- intersect(metrics, names(metric_labels))

  if (length(metrics) == 0)
    stop("None of the requested metrics found in segment data.", call. = FALSE)

  df$segment <- factor(df$segment, levels = df$segment)

  long_df <- df |>
    dplyr::select(segment, dplyr::all_of(metrics)) |>
    tidyr::pivot_longer(
      cols      = dplyr::all_of(metrics),
      names_to  = "metric",
      values_to = "value"
    ) |>
    dplyr::mutate(
      metric_label = metric_labels[metric],
      metric_label = factor(metric_label, levels = metric_labels[metrics])
    )

  title_str <- if (!is.null(lake_name)) {
    sprintf("%s \u2014 Longitudinal Profile", lake_name)
  } else {
    "Longitudinal Segment Profile"
  }

  ggplot2::ggplot(long_df,
                   ggplot2::aes(x = segment, y = value, group = 1)) +
    ggplot2::geom_line(color = "#1B5E8A", linewidth = 1.0) +
    ggplot2::geom_point(color = "#1B5E8A", fill = "white",
                         shape = 21, size = 3.5, stroke = 1.5) +
    ggplot2::facet_wrap(~ metric_label, scales = "free_y", ncol = 2) +
    ggplot2::labs(
      title    = title_str,
      subtitle = "Riverine \u2192 Lacustrine gradient (left to right)",
      x        = NULL,
      y        = NULL,
      caption  = "okBATHTUB R package"
    ) +
    ok_theme()
}


# =============================================================================
# 4. ok_plot_tsi() - Carlson TSI diagram
# =============================================================================

#' Plot a Carlson TSI deviation diagram
#'
#' @description
#' \code{ok_plot_tsi()} produces a Carlson (1977) TSI deviation diagram,
#' plotting TSI(TP) on the x-axis against TSI(Chl-a) and TSI(Secchi) on
#' the y-axis with trophic state background bands. Deviations from the
#' 1:1 line indicate light limitation (Chl-a below TP line) or non-algal
#' turbidity (Secchi below Chl-a line).
#'
#' Can accept either a single \code{okBATHTUB} result, or a data frame
#' containing the required TSI columns (e.g. from \code{ok_scenario()}
#' or a user-supplied observed-data summary).
#'
#' @param x An \code{okBATHTUB} object, or a data frame containing columns
#'   \code{tsi_tp}, \code{tsi_chla}, and optionally \code{tsi_secchi}.
#'   If a data frame, it may also contain \code{lake_name} and
#'   \code{eco_l3_name} for grouping.
#' @param color_by Character. Column name in a data frame to color points by.
#'   Common choices: \code{"eco_l3_name"}, \code{"trophic_state"},
#'   \code{"lake_name"}. Ignored when \code{x} is an \code{okBATHTUB} object.
#' @param lake_name Character. Lake name for the plot title when \code{x}
#'   is an \code{okBATHTUB} object.
#' @param show_diagonal Logical. Show the 1:1 reference line. Default
#'   \code{TRUE}.
#'
#' @return A \code{ggplot2} object.
#'
#' @examples
#' \dontrun{
#' # From a single pipeline result
#' result <- ok_load(inflow_m3yr = 45e6, tp_inflow_ugl = 120,
#'                    coefficients = "oklahoma",
#'                    ecoregion    = "Cross Timbers") |>
#'   ok_hydraulics(surface_area_ha = 890, mean_depth_m = 4.2) |>
#'   ok_retention() |>
#'   ok_inlake()    |>
#'   ok_tsi()
#' ok_plot_tsi(result, lake_name = "Arcadia Lake")
#'
#' # From observed AWQMS data
#' obs_tsi <- all_lakes |>
#'   dplyr::filter(!is.na(tp_ugl), !is.na(chla_ugl), !is.na(secchi_m)) |>
#'   dplyr::rowwise() |>
#'   dplyr::mutate(
#'     tsi_tp     = 14.42 * log(tp_ugl)   + 4.15,
#'     tsi_chla   = 9.81  * log(chla_ugl) + 30.6,
#'     tsi_secchi = 60.0  - 14.41 * log(secchi_m)
#'   )
#' ok_plot_tsi(obs_tsi, color_by = "eco_l3_name")
#' }
#'
#' @references
#' Carlson, R.E. (1977). A trophic state index for lakes.
#' \emph{Limnology and Oceanography}, 22(2), 361-369.
#'
#' @seealso \code{\link{ok_tsi}}, \code{\link{ok_tsi_observed}}
#' @export

ok_plot_tsi <- function(x,
                         color_by      = NULL,
                         lake_name     = NULL,
                         show_diagonal = TRUE) {

  if (!requireNamespace("ggplot2", quietly = TRUE))
    stop("Package 'ggplot2' is required.", call. = FALSE)
  if (!requireNamespace("tidyr", quietly = TRUE))
    stop("Package 'tidyr' is required.", call. = FALSE)
  if (!requireNamespace("dplyr", quietly = TRUE))
    stop("Package 'dplyr' is required.", call. = FALSE)

  pal    <- ok_trophic_colors()

  # Trophic state band data
  bands <- data.frame(
    xmin  = c(0,  40, 50, 70),
    xmax  = c(40, 50, 70, 100),
    ymin  = c(0,  40, 50, 70),
    ymax  = c(40, 50, 70, 100),
    state = c("Oligotrophic", "Mesotrophic", "Eutrophic", "Hypereutrophic")
  )

  # --- Build plot data from okBATHTUB object ---
  if (inherits(x, "okBATHTUB")) {

    d <- x$data
    plot_df <- data.frame(
      tsi_tp     = d$tsi_tp     %||% NA_real_,
      tsi_chla   = d$tsi_chla   %||% NA_real_,
      tsi_secchi = d$tsi_secchi %||% NA_real_,
      state      = d$trophic_state %||% NA_character_
    )

    title_str <- if (!is.null(lake_name)) {
      sprintf("%s \u2014 Carlson TSI Diagram", lake_name)
    } else {
      "Carlson TSI Diagram"
    }

    # Pivot to long for Chl-a and Secchi lines
    long_df <- tidyr::pivot_longer(
      plot_df,
      cols      = c(tsi_chla, tsi_secchi),
      names_to  = "tsi_type",
      values_to = "tsi_y"
    ) |>
    dplyr::mutate(
      tsi_type = dplyr::recode(tsi_type,
                                "tsi_chla"   = "TSI(Chl-a)",
                                "tsi_secchi" = "TSI(Secchi)")
    ) |>
    dplyr::filter(!is.na(tsi_y), !is.na(tsi_tp))

    p <- ggplot2::ggplot(long_df,
                          ggplot2::aes(x = tsi_tp, y = tsi_y,
                                       color = tsi_type, shape = tsi_type)) +
      ggplot2::geom_rect(
        data        = bands,
        ggplot2::aes(xmin = xmin, xmax = xmax,
                     ymin = ymin, ymax = ymax, fill = state),
        alpha       = 0.10,
        inherit.aes = FALSE
      ) +
      ggplot2::scale_fill_manual(values = pal, name = "Trophic State",
                                  guide = ggplot2::guide_legend(order = 2)) +
      ggplot2::geom_point(size = 4) +
      ggplot2::scale_color_manual(
        values = c("TSI(Chl-a)"   = "#1B5E8A",
                   "TSI(Secchi)"  = "#D9534F"),
        name   = NULL,
        guide  = ggplot2::guide_legend(order = 1)
      ) +
      ggplot2::scale_shape_manual(
        values = c("TSI(Chl-a)" = 16, "TSI(Secchi)" = 17),
        name   = NULL,
        guide  = ggplot2::guide_legend(order = 1)
      )

  } else if (is.data.frame(x)) {

    # --- Build plot data from data frame ---
    required <- c("tsi_tp", "tsi_chla")
    missing  <- setdiff(required, names(x))
    if (length(missing) > 0)
      stop(sprintf("Data frame missing required columns: %s",
                   paste(missing, collapse = ", ")), call. = FALSE)

    title_str <- if (!is.null(lake_name)) {
      sprintf("%s \u2014 Carlson TSI Diagram", lake_name)
    } else {
      "Carlson TSI Diagram"
    }

    plot_df <- x[!is.na(x$tsi_tp) & !is.na(x$tsi_chla), ]

    aes_map <- if (!is.null(color_by) && color_by %in% names(plot_df)) {
      ggplot2::aes(x = tsi_tp, y = tsi_chla,
                   color = .data[[color_by]])
    } else {
      ggplot2::aes(x = tsi_tp, y = tsi_chla)
    }

    p <- ggplot2::ggplot(plot_df, aes_map) +
      ggplot2::geom_rect(
        data        = bands,
        ggplot2::aes(xmin = xmin, xmax = xmax,
                     ymin = ymin, ymax = ymax, fill = state),
        alpha       = 0.10,
        inherit.aes = FALSE
      ) +
      ggplot2::scale_fill_manual(values = pal, name = "Trophic State",
                                  guide = ggplot2::guide_legend(order = 2)) +
      ggplot2::geom_point(alpha = 0.7, size = 2.5)

    if (is.null(color_by)) {
      p <- p + ggplot2::scale_color_manual(values = "#1B5E8A", guide = "none")
    }

  } else {
    stop("'x' must be an okBATHTUB object or a data frame.", call. = FALSE)
  }

  # 1:1 diagonal reference line
  if (show_diagonal) {
    p <- p +
      ggplot2::geom_abline(slope = 1, intercept = 0,
                            linetype = "dashed",
                            color    = "grey40",
                            linewidth = 0.6)
  }

  p <- p +
    ggplot2::coord_fixed(ratio = 1, xlim = c(0, 100), ylim = c(0, 100)) +
    ggplot2::labs(
      title    = title_str,
      subtitle = "Points above 1:1 line: algae-limited clarity | Below: non-algal turbidity",
      x        = "TSI(TP)",
      y        = if (inherits(x, "okBATHTUB")) "TSI(Chl-a) / TSI(Secchi)" else "TSI(Chl-a)",
      caption  = "okBATHTUB R package"
    ) +
    ok_theme()

  p
}
